### ISSUE TITLE
I might be off, but the random shuffle seems wrong?

### ISSUE THREAD

**Issue by davepermen** [jongalloway/BlazorMatchGame#1]
I tried to get it to build, but failed. The code reads like it will not distribute every animal 2x, but just randomly take them (possibly taking 1 more than once).

If so, a shuffle algorithm like this one might help (would've tested and sent a PR if i would've gotten it to work).

```csharp
public static IEnumerable<T> Randomize<T>(this IEnumerable<T> source)
{
    Random rnd = new Random();
    return source.OrderBy<T, int>((item) => rnd.Next());
}
```

from
https://stackoverflow.com/a/3456788

purely guessing

```csharp
private void SetUpGame()
{
    var shuffled = animalEmoji.Randomize();
    int index = 0;
    for (int row = 0; row < 3; row++)
    {
        for (int col = 0; col < 3; col++)
        {
            randomizedAnimals[row, col] = shuffled [index++];
        }
    }
}
```

so if that problem pops up, this might help.

**Comment by jongalloway** [comment]
I rewrote, using a simple OrderBy(random.Next) - which is slow, but the goal here is to keep it really simple.
